FROM rust:1.88

RUN : \
    && rustup component add clippy \
    && rustup component add rustfmt \
    && :

# RUN : \
#     && apt-get update \
#     && apt-get install -y docker.io docker-compose \
#     && :
