[package]
name = "aethernet-macros"
license.workspace = true
version.workspace = true
edition = "2024"

[lib]
proc-macro = true

[dependencies]
aethernet-macros-core = { path = "../aethernet-macros-core" }
