name: Aethernet - CI

on:
  # Always build main
  push:
    # TEMP: turn this back on for merge
    # branches:
    #   main
  # For pull requests
  pull_request:
  # Allow manually triggered runs
  workflow_dispatch:

jobs:
  run-build:
    name: Validate, run build, and tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: build docker conatiners
        run: docker compose build
      - name: Run build
        run: docker compose run rust
